apiVersion: v1 
kind: Service 
metadata: 
  name: example-oracle-svc
spec: 
  selector:
    app: oracle
  ports:
    - name: oracle-web 
      protocol: TCP 
      port: 82
      targetPort: 80  
  type: LoadBalancer