apiVersion: apps/v1 
kind: Deployment
metadata:
  name: example-oracle-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oracle 
  template:
    metadata:
      labels:
        app: oracle 
    spec: 
      containers:
        - name: oracle-cont 
          image: muralisocial123/oracle-web-app:latest
          ports:
            - containerPort: 80 
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi    
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: example-oracle-svc
spec: 
  selector:
    app: oracle
  ports:
    - name: oracle-web 
      protocol: TCP 
      port: 82
      targetPort: 80 
  type: ClusterIP            

