apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: oracle-web-app-rs 
  labels:
    app: example
spec: # It defines the behaviour of the ReplicaSet
  replicas: 3
  selector:
    matchLabels:
      web: app
  template: # Define the Pod defination
    metadata:
      labels:
        web: app 
        name: mohan 
    spec: # It defines the behaviour of the Pod 
      containers:
        - name: test-web 
          image: muralisocial123/oracle-web-app:latest
          ports:
            - containerPort: 80     
